token          = "xxx-xxx--BJz7gKLXFVhEJU3vHUU6DkzKT3etxxxxxxxx"
subnetid       = "subnet-0f8ff994c9cxxxxxx"
security_group = "sg-07f5fe497f0xxxxxx"
region         = "us-east-2"
account        = "account-xxxxxxxxxx"
